version: 2.1

jobs:
  build:
    parameters:
      aurpkg:
        type: string
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build PKG
          command: |
            docker run --name=build_<< parameters.aurpkg >> eyenx/aurbuilder:latest << parameters.aurpkg >> 
      - run:
          name: get built PKG
          command: |
            docker cp build_<< parameters.aurpkg >>:/export/ . 
      - run:
          name: scp built PKG
          command: |
            for pkg in export/*pkg.tar.xz; do echo put $pkg | sftp -b- -o "StrictHostKeyChecking=no" -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_HOST}:${SFTP_DIR}; done

workflows:
  all-builds:
    jobs:
      - build:
          filters:
            branches:
              only: master
          matrix:
            parameters:
              aurpkg:
                - "auracle-git"
                - "bash-pipes"
                - "beautysh"
                - "circleci-cli-bin"
                - "cloudfoundry-cli"
                - "conky-cli"
                - "connect"
                - "debtap"
                - "drone-cli"
                - "gkeyring"
                - "grepcidr"
                - "gtk-recordmydesktop"
                - "gnunet-gtk"
                - "icaclient"
                - "insomnia"
                - "ipfs-paste"
                - "ipfs-screencap"
                - "irssi-scripts-git"
                - "ix"
                - "jitsi"
                - "joplin"
                - "keybase-bin"
                - "keys-pub"
                - "kubectl-bin"
                - "kustomize-bin"
                - "lbdb"
                - "mimeo"
                - "mons"
                - "nodejs-commitizen"
                - "nodejs-cz-conventional-changelog"
                - "nodejs-dat"
                - "notifymuch-git"
                - "pairing_tool"
                - "phantomjs-bin"
                - "pypy3-httplib2"
                - "python-notify2"
                - "python-openshift"
                - "python2-gnomekeyring"
                - "python2-j2cli"
                - "python2-oauth2client"
                - "python2-rsa"
                - "rxvt-unicode-patched"
                - "siji-git"
                - "spotify"
                - "spotify-tui"
                - "spotifyd-full"
                - "stern-bin"
                - "timg"
                - "tmuxinator"
                - "tor-browser"
                - "ttf-font-awesome-4"
                - "ttf-weather-icons"
                - "tty-clock"
                - "twmn-git"
                - "vault-client"
                - "websockify"
                - "whalebrew"
                - "wpa_actiond"
                - "yay"
                - "zoom"
