version: 2.1

jobs:
  build:
    parameters:
      aurpkg:
        type: string
    docker:
      - image: docker
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build PKG
          command: |
            docker run --name=build_<< parameters.aurpkg >> eyenx/aurbuilder:latest << parameters.aurpkg >> 
      - run:
          name: get built PKG
          command: |
            docker cp build_<< parameters.aurpkg >>:/export/ . 
      - run:
          name: scp built PKG
          command: |
            echo put export/<< parameters.aurpkg >>*pkg.tar.xz  | sftp -b- -o "StrictHostKeyChecking=no" -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_HOST}:${SFTP_DIR}

workflows:
  all-builds:
    jobs:
      - build:
          matrix:
            parameters:
              aurpkg:
                - "auracle-git"
                - "bash-pipes"

