name: "build-aurpkgs"
on: 
  push:
    branches:
    - 'master'

jobs:
  aurpkg-build:
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
            aurpkg:
              - "auracle-git"
              - "bash-pipes"
              - "beautysh"
              - "circleci-cli-bin"
              - "cloudfoundry-cli"
              - "conky-cli"
              - "connect"
              - "debtap"
              - "drone-cli"
              - "grepcidr"
              - "gtk-recordmydesktop"
              - "gnunet-gtk"
              - "helm-docs"
              - "icaclient"
              - "insomnia"
              - "ipfs-paste"
              - "ipfs-screencap"
              - "irssi-scripts-git"
              - "ix"
              - "jitsi"
              - "joplin"
              - "keybase-bin"
              - "keys-pub"
              - "kubectl-bin"
              - "kustomize-bin"
              - "lbdb"
              - "mimeo"
              - "mons"
              - "ncspot"
              - "nodejs-commitizen"
              - "nodejs-commitizen"
              - "nodejs-cz-conventional-changelog"
              - "nodejs-dat"
              - "notifymuch-git"
              - "pairing_tool"
              - "phantomjs-bin"
              - "pypy3-httplib2"
              - "python-notify2"
              - "python-openshift"
              - "python2-gnomekeyring"
              - "python2-j2cli"
              - "python2-oauth2client"
              - "python2-rsa"
              - "rxvt-unicode-patched"
              - "siji-git"
              - "spotify"
              - "sshrc"
              - "sslyze"
              - "stern-bin"
              - "timg"
              - "tmuxinator"
              - "tor-browser"
              - "ttf-font-awesome-4"
              - "ttf-weather-icons"
              - "tty-clock"
              - "twmn-git"
              - "vault-client"
              - "websockify"
              - "whalebrew"
              - "wpa_actiond"
              - "yay"
              - "zoom"
    steps:
    - uses: actions/checkout@v1
    - name:  build all
      run: |
        docker run --name=build_${{ matrix.aurpkg }} eyenx/aurbuilder:latest ${{ matrix.aurpkg }}
    - run: |
        docker cp build_${{ matrix.aurpkg }}
    - run: |
        docker cp b ild_${{ matrix.aurpkg }}
    - run: |
        for pkg in export/*pkg.tar.xz; do echo put $pkg | sftp -b- -o "StrictHostKeyChecking=no" -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_HOST}:${SFTP_DIR}; done

