name: "build"
on: 
  schedule:
    - cron: '3 2 * * *'
  push:
    branches:
    - 'master'

jobs:
  aurpkg-build:
    runs-on: ubuntu-latest
    steps:
    - name:  prepare environment
      run: |
        mkdir $HOME/.ssh && echo $SSH_KEY | base64 -d  > $HOME/.ssh/id_rsa && chmod 0700 $HOME/.ssh && chmod 0600 $HOME/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name:  build ${{ matrix.aurpkg }}
      run: |
        docker run -e ADD_GPG_KEYS="4773BD5E130D1D45 1D1F0DC78F173680 EB774491D9FF06E2" --name=build_${{ matrix.aurpkg }} ghcr.io/eyenx/aurbuilder:latest ${{ matrix.aurpkg }}
    - name:  cp pkg out of container
      run: |
        docker cp build_${{ matrix.aurpkg }}:/export/ .

    - uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.aurpkg }} 
        path: export/${{ matrix.aurpkg }}.pkg.tar.*

    - name:  copy pkg via sftp
      run: |
        for pkg in export/*.pkg.tar.*; do echo put $pkg | sftp -b- -o "StrictHostKeyChecking=no" -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_HOST}:${SFTP_DIR} &>/dev/null; done
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_USER: ${{ secrets.SFTP_USER }}
        SFTP_DIR: ${{ secrets.SFTP_DIR }}

    strategy:
        fail-fast: false
        matrix:
            aurpkg:
              - "auracle-git"
              - "azure-cli"
              - "bash-pipes"
              - "beautysh"
              - "brave-bin"
              - "brig"
              - "circleci-cli-bin"
              - "cloudfoundry-cli"
              - "conky-cli"
              - "connect"
              - "ctlptl-bin"
              - "debtap"
              - "dockfmt"
              - "epson-inkjet-printer-escpr"
              - "finja"
              - "gitlab-glab-bin"
              - "gnome-shell-extension-taskwhisperer"
              - "gofumpt-git"
              - "golangci-lint"
              - "gomplate-git"
              - "google-cloud-sdk"
              - "grepcidr"
              - "gtk-recordmydesktop"
              - "grpcurl-bin"
            # - "haskell-jet-git"
              - "helm-docs"
              - "icaclient"
              - "insomnia"
              - "ipfs-paste"
              - "ipfs-screencap"
              - "irssi-scripts-git"
              - "ix"
              - "jitsi-meet-desktop-bin"
              - "joplin"
            # - "joplin-desktop"
              - "jsonnet-bundler-bin"
              - "jsonnet"
              - "k0s-bin"
              - "k0sctl-bin"
              - "keybase-bin"
              - "keys-pub"
              - "kubepug-bin"
              - "kubeval-bin"
              - "kubeswitch-bin"
              - "kustomize-bin"
              - "lbdb"
              - "mimeo"
              - "mons"
              - "mpris-scrobbler"
              - "ncpamixer"
              - "ncspot"
              - "nerdctl-bin"
              - "nerdctl-git"
              - "nodejs-commitizen"
              - "nodejs-cz-conventional-changelog"
              - "nodejs-cz-emoji"
              - "nodejs-dat"
              - "nodejs-jsondiffpatch"
              - "notifymuch-git"
              - "pairing_tool"
              - "phantomjs-bin"
              - "phetch"
              - "pinentry-dmenu"
              - "pluto"
              - "polaris-bin"
              - "pypy3-httplib2"
              - "python-openshift"
              - "python2-j2cli"
              - "python2-oauth2client"
              - "python2-rsa"
              - "rancher-k3d-bin"
              - "rke-bin"
              - "rootlesskit-bin"
              - "siji-git"
              - "ssb-patchwork"
            # - "ssb-server"
              - "sshrc"
            # - "sslyze"
              - "stern-bin"
              - "tamzen-font"
              - "threema-desktop"
              - "timg"
              - "tmuxinator"
              - "tor-browser"
              - "ttf-font-awesome-4"
              - "ttf-weather-icons"
            # - "tty-clock"
              - "twmn-git"
              - "velero-bin"
              - "waypoint-bin"
              - "webdump-git"
              - "websockify"
              - "whalebrew"
              - "wpa_actiond"
              - "xcursor-retrosmart"
              - "yay"
              - "yh-bin"
              - "yml2dot"
