name: "build"
on: 
  schedule:
    - cron: '3 22 * * *'
  push:
    branches:
    - 'master'

jobs:
  aurpkg-build:
    runs-on: ubuntu-latest
    steps:
    - name:  prepare environment
      run: |
        mkdir $HOME/.ssh && echo $SSH_KEY | base64 -d  > $HOME/.ssh/id_rsa && chmod 0700 $HOME/.ssh && chmod 0600 $HOME/.ssh/id_rsa
      env:
        SSH_KEY: ${{ secrets.SSH_KEY }}
    - name:  build ${{ matrix.aurpkg }}
      run: |
        docker run -e ADD_GPG_KEYS="4773BD5E130D1D45 1D1F0DC78F173680 EB774491D9FF06E2" --name=build_${{ matrix.aurpkg }} eyenx/aurbuilder:latest ${{ matrix.aurpkg }}
    - name:  cp pkg out of container
      run: |
        docker cp build_${{ matrix.aurpkg }}:/export/ .
    - name:  copy pkg via sftp
      run: |
        for pkg in export/*.pkg.tar.*; do echo put $pkg | sftp -b- -o "StrictHostKeyChecking=no" -P ${SFTP_PORT} ${SFTP_USER}@${SFTP_HOST}:${SFTP_DIR} &>/dev/null; done
      env:
        SFTP_HOST: ${{ secrets.SFTP_HOST }}
        SFTP_PORT: ${{ secrets.SFTP_PORT }}
        SFTP_USER: ${{ secrets.SFTP_USER }}
        SFTP_DIR: ${{ secrets.SFTP_DIR }}
    strategy:
        fail-fast: false
        matrix:
            aurpkg:
              - "auracle-git"
              - "azure-cli"
              - "bash-pipes"
              - "beautysh"
              - "brig"
              - "bpytop"
              - "circleci-cli-bin"
              - "cloudfoundry-cli"
              - "conky-cli"
              - "connect"
              - "debtap"
              - "dockfmt"
              - "drone-cli"
              - "finja"
              - "gnome-shell-extension-taskwhisperer"
              - "gomplate-git"
              - "google-cloud-sdk"
              - "grepcidr"
              - "gtk-recordmydesktop"
              - "gnunet-gtk"
              - "grpcurl-bin"
              - "helm-docs"
              - "hub-bin"
              - "icaclient"
              - "insomnia"
              - "ipfs-paste"
              - "ipfs-screencap"
              - "irssi-scripts-git"
              - "ix"
              - "jitsi"
              - "joplin"
              - "jsonnet-bundler-bin"
              - "jsonnet"
              - "keybase-bin"
              - "keys-pub"
              - "kubectl-bin"
              - "kubernetes-helm2"
              - "kustomize-bin"
              - "lbdb"
              - "mimeo"
              - "mons"
              - "mpris-scrobbler"
              - "ncspot"
              - "networkmanager-l2tp"
              - "nodejs-commitizen"
              - "nodejs-cz-conventional-changelog"
              - "nodejs-cz-emoji"
              - "nodejs-cz-gitmoji"
              - "nodejs-dat"
              - "nodejs-jsondiffpatch"
              - "notifymuch-git"
              - "pairing_tool"
              - "phantomjs-bin"
              - "polaris-bin"
              - "pypy3-httplib2"
              - "python-cssutils"
              - "python-openshift"
              - "python2-gnomekeyring"
              - "python2-j2cli"
              - "python2-oauth2client"
              - "python2-rsa"
              - "rancher-k3d-bin"
              - "siji-git"
              - "ssb-server"
              - "sshrc"
              - "sslyze"
              - "stern-bin"
              - "st-luke-git"
              - "timg"
              - "tmuxinator"
              - "tor-browser"
              - "ttf-font-awesome-4"
              - "ttf-weather-icons"
              - "tty-clock"
              - "twmn-git"
              - "vault-client"
              - "velero-bin"
              - "waypoint-bin"
              - "websockify"
              - "whalebrew"
              - "wpa_actiond"
              - "yay"
              - "yh-bin"
